# Generated by Django 2.2.4 on 2019-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('os', models.IntegerField(choices=[(1, 'android'), (2, 'ios')])),
                ('impressions', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('installs', models.PositiveIntegerField()),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
                ('cpi', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
